export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const REMOVE_BOOK_SUCCESS = 'REMOVE_BOOK_SUCCESS';
export const LOAD_MY_BOOKS_SUCCESS = 'LOAD_MY_BOOKS_SUCCESS';
export const UNLOAD_MY_BOOKS = 'UNLOAD_MY_BOOKS';
export const REQUEST_BOOK_SUCCESS = 'REQUEST_BOOK_SUCCESS';

export const SEARCH_FOR_BOOK_SUCCESS = 'SEARCH_FOR_BOOK_SUCCESS';
export const CHANGE_SEARCH_CRITERIA = 'CHANGE_SEARCH_CRITERIA';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';